In [1]:
import DMN3 as DMN
from matplotlib import pyplot as plt
import numpy as np
from helperfuncs import *

In [2]:
node = DMN.Node(np.ones(6)*2)
node.compliance
node.rotated_compliance = node.compliance

node.left = DMN.Node(np.array([0.7243458035427647,-0.6624489424587073,0.0,0.7243458035427647,0.0,2.7735894920029462]))
node.right = DMN.Node(np.array([0.36757546481294456,-0.16233746963686535,0.0,0.3675754648129446,0.0,1.05982586889962]))

node.right.rotated_compliance = node.right.compliance
node.left.rotated_compliance = node.left.compliance

node.rotated_compliance = homogenise(node.left.rotated_compliance, node.right.rotated_compliance,0.2,0.8)

In [3]:
node.sigma = np.ones(3)*2
DMN.update_stress(node)



In [4]:
node.right.sigma

array([2.21854509, 2.        , 2.        ])

In [5]:
node.left.sigma

array([1.12581965, 2.        , 2.        ])

In [6]:
DMN.calc_elasto_plastic_operator(node),convert_vectorised(node.rotated_compliance)

0.06051266315562544 [[14.01714523 14.72461602 10.67732769]
 [14.72461602 15.46779413 11.21623182]
 [10.67732769 11.21623182  8.13327712]] [3.74394781 3.93291166 2.8518901 ] [[3.55672645 2.05919527 0.        ]
 [2.05919527 3.84017222 0.        ]
 [0.         0.         0.71297252]]


(array([[-5.00399959e+14, -5.00399959e+14, -3.00239975e+15],
        [-5.00399959e+14, -5.00399959e+14, -3.00239975e+15],
        [-3.00239975e+15, -3.00239975e+15, -1.80143985e+16]]),
 array([[ 0.40774137, -0.218641  ,  0.        ],
        [-0.218641  ,  0.3776457 ,  0.        ],
        [ 0.        ,  0.        ,  1.40257859]]))