In [1]:
import DMN3 as DMN
from matplotlib import pyplot as plt
import numpy as np
from helperfuncs import *

In [2]:
node = DMN.Node(np.ones(6)*2)
node.compliance
node.rotated_compliance = node.compliance
p1 = np.array([0.7243458035427647,-0.6624489424587073,0.0,0.7243458035427647,0.0,2.7735894920029462])
p2 = np.array([0.36757546481294456,-0.16233746963686535,0.0,0.3675754648129446,0.0,1.05982586889962])

node.left = DMN.Node(p1)
node.right = DMN.Node(p2)

node.right.rotated_compliance = node.right.compliance
node.left.rotated_compliance = node.left.compliance

node.rotated_compliance = homogenise(node.left.rotated_compliance, node.right.rotated_compliance,0.2,0.8)

In [3]:
node.sigma = np.ones(3)*2
DMN.update_stress(node)



In [4]:
node.right.sigma

array([2.21854509, 2.        , 2.        ])

In [5]:
node.left.sigma

array([1.12581965, 2.        , 2.        ])

In [6]:
DMN.calc_elasto_plastic_operator(node),convert_vectorised(node.rotated_compliance)

(array([[ 0.40774137, -0.218641  ,  0.        ],
        [-0.218641  ,  0.3776457 ,  0.        ],
        [ 0.        ,  0.        ,  1.40257859]]),
 array([[ 0.40774137, -0.218641  ,  0.        ],
        [-0.218641  ,  0.3776457 ,  0.        ],
        [ 0.        ,  0.        ,  1.40257859]]))

In [7]:
res1 = np.ones((3,))* 2
res2 = np.ones((3,))  * 4

In [8]:
homogenise_res(node.left.rotated_compliance,node.right.rotated_compliance,0.5,0.5,res1,res2)

array([3.32673632, 2.54198944, 3.        ])

In [9]:
Model = DMN.Tree(3)
root = Model.initialise()

Model.propagate_weights(root)
Model.initialise_bottom_layer(root,p1,p2)


In [10]:
Model.homogenise_system_res(root,p1,p2)


In [11]:
root.res_strain,root.eps

(array([ 0.25008899, -0.37441426,  0.11354192]), array([0., 0., 0.]))

In [12]:
root.sigma = np.array([1,2,3])
Model.backwards_pass(root)

Updating stress of nodes:  (1, 1) (1, 2)
Updating the strain of node:  0 1
Updating stress of nodes:  (2, 1) (2, 2)
Updating the strain of node:  1 1
Updating stress of nodes:  (2, 3) (2, 4)
Updating the strain of node:  1 2
Updating stress of nodes:  (3, 1) (3, 2)
Updating the strain of node:  2 1
Updating stress of nodes:  (3, 3) (3, 4)
Updating the strain of node:  2 2
Updating stress of nodes:  (3, 5) (3, 6)
Updating the strain of node:  2 3
Updating stress of nodes:  (3, 7) (3, 8)
Updating the strain of node:  2 4
Updating the strain of node:  3 1
Updating the strain of node:  3 2
Updating the strain of node:  3 3
Updating the strain of node:  3 4
Updating the strain of node:  3 5
Updating the strain of node:  3 6
Updating the strain of node:  3 7
Updating the strain of node:  3 8


In [13]:
bottom_node = Model.fetch_node(root,3,6)

In [14]:
bottom_node.sigma,bottom_node.eps

(array([1.23001314, 2.        , 3.        ]),
 array([0.2186287 , 0.7501841 , 1.73450636]))